global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway-service:8000"]

  - job_name: "order"
    static_configs:
      - targets: ["order-service:8000"]

  - job_name: "payment"
    static_configs:
      - targets: ["payment-service:8000"]

  - job_name: "notification"
    static_configs:
      - targets: ["notification-service:8000"]
